---
- name: Install unzip
  apt: pkg=unzip state=latest

- name: create gradle directory
  shell: mkdir -p /gradle

- name: get gradle directory
  shell: ls /gradle
  register: gradle_directory

- name: create gradle packages directory
  command: mkdir -p /gradle/packages
  when: "gradle_directory.stdout.find('gradle-1.12') == -1"

- name: download gradle zip
  get_url: url=https://services.gradle.org/distributions/gradle-1.12-bin.zip dest=/gradle/packages
  when: "gradle_directory.stdout.find('gradle-1.12') == -1"

- name: unzip gradle
  shell: unzip /gradle/packages/gradle-1.12-bin.zip -d /gradle
  when: "gradle_directory.stdout.find('gradle-1.12') == -1"